In [8]:
import numpy as np
import pandas as pd

In [8]:
list1= np.array([1,2,3,4,5])
list2= np.array([6,7,8,9,10 ])
list1 + list2

array([ 7,  9, 11, 13, 15])

In [7]:
np.random.rand(2,3,4 )

array([[[0.90031777, 0.98069896, 0.19623192, 0.01658126],
        [0.06218947, 0.8773204 , 0.90855572, 0.30200074],
        [0.8064339 , 0.74058324, 0.35786432, 0.44602243]],

       [[0.47495919, 0.00462252, 0.64309214, 0.69933698],
        [0.97429538, 0.79121173, 0.03095559, 0.42414437],
        [0.30953094, 0.40629945, 0.1629822 , 0.24685294]]])

In [7]:
np.array([1,2,3,4,4])

array([1, 2, 3, 4, 4])

In [26]:
array1= np.array([1,2,3,4,4])
array2= np.array([5,6,7,8,9])
array3= np.concatenate((array1,array2))
np.split(array3,[5,8,9])

[array([1, 2, 3, 4, 4]), array([5, 6, 7]), array([8]), array([9])]

array([1, 2, 3, 4, 4])

In [10]:
variable1=pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])

In [11]:
variable1.items

<bound method Series.items of a    1
b    2
c    3
d    4
e    5
dtype: int64>

In [13]:
for index, value in variable1.items():
    print(f"Index: {index}, Value: {value}")


Index: a, Value: 1
Index: b, Value: 2
Index: c, Value: 3
Index: d, Value: 4
Index: e, Value: 5


In [9]:
a=np.random.randint(2,40 ,size=9)
b=np.random.randint(2,40 ,size=9)
c=np.random.randint(2,40 ,size=9)
d=np.random.randint(2,40 ,size=9)
df_frame={'Val1':a,'Val2':b,'val3':c,'Val4':d}
df=pd.DataFrame(df_frame)

In [32]:
df.head(2)
df.tail(3)


Val1  Val2  val3  Val4
6    23    34    28     4
7    32    38     3    28
8    20    35    25    16

In [17]:
df['Val5']=[2,3,4,5,6,7,8,9,10]
df

Val1  Val2  val3  Val4  Val5
0    26     9    19    17     2
1     8    31    18    17     3
2    19    17    26    16     4
3    39    10    20    10     5
4    15    31    29     7     6
5    24    35    14     5     7
6    15    35    30    34     8
7    32     5    11     2     9
8    26    31    38    32    10

In [23]:
Val1=np.array([1,2,np.nan,4,5])
Val2= np.array([6,np.nan,8,9,10])
Country= np.array(["Germany","France","Italy","Spain","Portugal"])


In [25]:
df=pd.DataFrame({"Val1":Val1, "Val2":Val2, "Country":Country})
df

Val1  Val2   Country
0   1.0   6.0   Germany
1   2.0   NaN    France
2   NaN   8.0     Italy
3   4.0   9.0     Spain
4   5.0  10.0  Portugal

In [27]:
df.dropna()

Val1  Val2   Country
0   1.0   6.0   Germany
3   4.0   9.0     Spain
4   5.0  10.0  Portugal

In [28]:
df.dropna(axis=1)

Country
0   Germany
1    France
2     Italy
3     Spain
4  Portugal

In [29]:
df.dropna(how='all')

Val1  Val2   Country
0   1.0   6.0   Germany
1   2.0   NaN    France
2   NaN   8.0     Italy
3   4.0   9.0     Spain
4   5.0  10.0  Portugal

In [31]:
df['val3']=np.nan
df

Val1  Val2   Country  val3
0   1.0   6.0   Germany   NaN
1   2.0   NaN    France   NaN
2   NaN   8.0     Italy   NaN
3   4.0   9.0     Spain   NaN
4   5.0  10.0  Portugal   NaN

Val1  Val2   Country  val3
0   1.0   6.0   Germany   NaN
1   2.0   NaN    France   NaN
2   NaN   8.0     Italy   NaN
3   4.0   9.0     Spain   NaN
4   5.0  10.0  Portugal   NaN

In [36]:
df.dropna(axis=1 , how='all')

Val1  Val2   Country
0   1.0   6.0   Germany
1   2.0   NaN    France
2   NaN   8.0     Italy
3   4.0   9.0     Spain
4   5.0  10.0  Portugal

In [37]:
df


Val1  Val2   Country  val3
0   1.0   6.0   Germany   NaN
1   2.0   NaN    France   NaN
2   NaN   8.0     Italy   NaN
3   4.0   9.0     Spain   NaN
4   5.0  10.0  Portugal   NaN

In [39]:
df = df.dropna(axis=1 , how='all')
df

Val1  Val2   Country
0   1.0   6.0   Germany
1   2.0   NaN    France
2   NaN   8.0     Italy
3   4.0   9.0     Spain
4   5.0  10.0  Portugal

In [40]:
df

Val1  Val2   Country
0   1.0   6.0   Germany
1   2.0   NaN    France
2   NaN   8.0     Italy
3   4.0   9.0     Spain
4   5.0  10.0  Portugal