In [3]:
import numpy as np
import pandas as pd

In [8]:
list1= np.array([1,2,3,4,5])
list2= np.array([6,7,8,9,10 ])
list1 + list2

array([ 7,  9, 11, 13, 15])

In [7]:
np.random.rand(2,3,4 )

array([[[0.90031777, 0.98069896, 0.19623192, 0.01658126],
        [0.06218947, 0.8773204 , 0.90855572, 0.30200074],
        [0.8064339 , 0.74058324, 0.35786432, 0.44602243]],

       [[0.47495919, 0.00462252, 0.64309214, 0.69933698],
        [0.97429538, 0.79121173, 0.03095559, 0.42414437],
        [0.30953094, 0.40629945, 0.1629822 , 0.24685294]]])

In [7]:
np.array([1,2,3,4,4])

array([1, 2, 3, 4, 4])

In [26]:
array1= np.array([1,2,3,4,4])
array2= np.array([5,6,7,8,9])
array3= np.concatenate((array1,array2))
np.split(array3,[5,8,9])

[array([1, 2, 3, 4, 4]), array([5, 6, 7]), array([8]), array([9])]

array([1, 2, 3, 4, 4])

In [10]:
variable1=pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])

In [11]:
variable1.items

<bound method Series.items of a    1
b    2
c    3
d    4
e    5
dtype: int64>

In [13]:
for index, value in variable1.items():
    print(f"Index: {index}, Value: {value}")


Index: a, Value: 1
Index: b, Value: 2
Index: c, Value: 3
Index: d, Value: 4
Index: e, Value: 5


In [27]:
a=np.random.randint(2,40 ,size=9)
b=np.random.randint(2,40 ,size=9)
c=np.random.randint(2,40 ,size=9)
d=np.random.randint(2,40 ,size=9)
df_frame={'Val1':a,'Val2':b,'val3':c,'Val4':d}
df=pd.DataFrame(df_frame)
df

Val1  Val2  val3  Val4
0    10    38    12     8
1    37    19    28     6
2    18    34     9    31
3    31     8    36     3
4     2    26     4     5
5    30     8     2    25
6    23    34    28     4
7    32    38     3    28
8    20    35    25    16

In [32]:
df.head(2)
df.tail(3)


Val1  Val2  val3  Val4
6    23    34    28     4
7    32    38     3    28
8    20    35    25    16